"""Initial schema

Revision ID: e93d24105967
Revises: 
Create Date: 2026-03-16 15:58:02.440250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e93d24105967'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('clothing_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('colors', sa.JSON(), nullable=False),
    sa.Column('styles', sa.JSON(), nullable=False),
    sa.Column('season', sa.String(length=50), nullable=False),
    sa.Column('formality', sa.String(length=50), nullable=False),
    sa.Column('material', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clothing_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clothing_items_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_clothing_items_user_id'), ['user_id'], unique=False)

    op.create_table('outfits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('weather_context', sa.JSON(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outfits_user_id'), ['user_id'], unique=False)

    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferred_styles', sa.JSON(), nullable=False),
    sa.Column('preferred_colors', sa.JSON(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('disliked_items', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('outfit_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outfit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reaction', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('outfit_id', 'user_id', name='uq_outfit_feedback_user')
    )
    with op.batch_alter_table('outfit_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outfit_feedback_outfit_id'), ['outfit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outfit_feedback_user_id'), ['user_id'], unique=False)

    op.create_table('outfit_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outfit_id', sa.Integer(), nullable=False),
    sa.Column('clothing_item_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['clothing_item_id'], ['clothing_items.id'], ),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outfit_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outfit_items_clothing_item_id'), ['clothing_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outfit_items_outfit_id'), ['outfit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outfit_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outfit_items_outfit_id'))
        batch_op.drop_index(batch_op.f('ix_outfit_items_clothing_item_id'))

    op.drop_table('outfit_items')
    with op.batch_alter_table('outfit_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outfit_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_outfit_feedback_outfit_id'))

    op.drop_table('outfit_feedback')
    op.drop_table('user_preferences')
    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outfits_user_id'))

    op.drop_table('outfits')
    with op.batch_alter_table('clothing_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clothing_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_clothing_items_category'))

    op.drop_table('clothing_items')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
